id: I40249137
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:04:33+00:00'
last_modified: '2022-06-08T12:34:17.579203+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9893
  title: དབུ་མའི་སྟོང་ཐུན་སྐལ་བཟང་མིག་འབྱེད་ཀྱི་གསུང་རྒྱུན་ཟླ་བའི་ཞལ་ལུང་དང་དབུ་མ་འཇུག་པའི་འབྲུ་འགྲེལ་བློ་གསལ་དགའ་བའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C40A:
      image_group_id: I1KG13048
      title: ''
      total_pages: 482
      order: 1
      base_file: C40A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
