id: opecha:P009650
initial_creation_type: ocr
source_metadata:
  id: bdr:W9893
  title: དབུ་མའི་སྟོང་ཐུན་སྐལ་བཟང་མིག་འབྱེད་ཀྱི་གསུང་རྒྱུན་ཟླ་བའི་ཞལ་ལུང་དང་དབུ་མ་འཇུག་པའི་འབྲུ་འགྲེལ་བློ་གསལ་དགའ་བའི་མེ་ལོང་།
  volume: ''
  author: ''
